apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/jellyfin
    repoURL: https://github.com/jellyfin/jellyfin-helm.git
    targetRevision: 1bf4aa842ddf0b2dba8403aa72532b543f42489c
    helm:
      releaseName: jellyfin
      valuesObject:
        image:
          # -- Container image repository for Jellyfin.
          repository: docker.io/jellyfin/jellyfin
          # -- Jellyfin container image tag. Leave empty to automatically use the Chart's app version.
          tag: "12"
          # -- Image pull policy (Always, IfNotPresent, or Never).
          pullPolicy: IfNotPresent
        persistence:
          media:
            size: "2Gi"
        ingress: 	{"annotations":{},"className":"nginx","enabled":true,"hosts":[{"host":"jellyfin.anymus.pro","paths":[{"path":"/","pathType":"ImplementationSpecific"}]}],"tls":[]}
        jellyfin:
          enableDLNA: true
        volumes:
          - name: external-media
            nfs:
              server: "192.168.0.212"
              path: "/"
        volumeMounts:
          - name: external-media
            mountPath: "/externalmedia"
