apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: jellyfin
    repoURL: https://jellyfin.github.io/jellyfin-helm
    targetRevision: 2.3.0
    helm:
      releaseName: argocd
      valuesObject:
        ingress: 	{"annotations":{},"className":"nginx","enabled":true,"hosts":[{"host":"jellyfin.anymus.pro","paths":[{"path":"/","pathType":"ImplementationSpecific"}]}],"tls":[]}
        jellyfin:
          enableDLNA: true
        volumes:
          - name: media
            nfs:
              server: "192.168.0.212"
              path: "/"
        volumeMounts:
          - name: media
            mountPath: "/media"