apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  encryptedData:
    client_id: AgCRWdfev3QAFVMgvHW4igP6JgE1MTwkWJbX2InvWxhbGw0xL1VUfvGgx1pocexKLVvKPTBGhet5zQO1d8SaKL+Vds8lF+ykSHKEvkCLJKlTw3lP+6YgBcFNAHeR6rm12L3JRjRv6uk8UVuIBPnOBpPhR/k5oLLTfHzVXjaP255lad3GQO0DIMBnLCbWDYaQGx0WXCGS4ifbH9NELHWvv4sBNMyCRxcBTu1sYqZmFgZqFcwuRN9emyvNMzDaO15KT+4Igd2wu4mJmEHdqW5rs0HFMdpHnhil+LLNRYgShbhYt5yz3gbev3fi8UIfKmngZN/gBHn8Qw490efrvt3cp9SzYEjdEYbYiNFRwxlIdxxYTmR1KipnhuH8mam3xCQoSoaRZvADJnq3gw68JAD1wdR58T4x/FweY6CGpKIPMXF39rTvqyqb4yT/RV9tdSyROrpuoQYAzyqsQaE2arFFykS2HfCapvswwJREOQ290Jj+BZmNRBs4dtxCxAoVCPAmqsiv8UqBBRzTc8sXmUOk3DYLZVNRSL9HnKa6MGOegGjpCGwxBlMABUPZ3SQvQnOrXuT9WpfjR8GfdfD3jzQ2C61s3cnZwTWcAe9XjS6gn0OLgVtpfU0n+PDvcFlHkdbU0zgNHdww33pilNQbigt0i4mcSkPB0ybovzrhHZabKmGT8eDZGQq2pLlZHyMDQSVjpq3oO7dOJf6y+PQjjDE/kWv00Q==
    client_secret: AgAZUwoJ0GDAemRM/nfO2/oCUpdkXeE5gcIPZ7CMZ1phwkGfajTp9Q/PdH5ZFqJwYhB97qnIdgq0+8Og5kIPVxrtK/BetzwaB1fBurF0ilA3RvaCkFQHVhJNPxFpSF0fyAzCNSqd/HP/Wgn9dgQOazFlHzr5wq1dDUxawtMUVxevNIV4VCH6YYM09qmlZbQcQfXbriq9WH37moPAXuv2kKdw9qgIQcgy0I4Y3z44QoMwWV/0Qp+MCK4Pazg4Q8j/8XLkpx4LU9nwyeUtDIhmD4WX4SHGD38JUOULmtGD1BsW5Iri0yIOdazPtkHoGkklNv7X6yiCVCr+i7SthRiHOBDAgxw+4DDHgxmacMYW+OsI2HdJ+H/271RXSvoI/IQ5+JvSUG+A8fP/EDjLyz0W0NIJ5eVwYAKXwwMtCu2rbnFEYY7s97H5EpefH+AdAQqQ5d+tAzSqztsV9MQpccQGM8lZrrQBlcOEF152EY9H5hxMPy8Hm/PL573fAIKasQFxyRYHykfsWUF3BBs2fICS61I0kykY1/4QcXRTvK2KxrQHXLSV9dxlvU2dUvaJPzNfQPvIViwEJWTWi0jwtvygSVznyXnIPjUDHMrxI3OaQCDOPOmBQYLYXai4SLcBT3lU1Nb9k29zpp0E2DnvTDklDGNAHYYBGjezJ/Kq48aqRzQPis6FpJ1xvTkf0OQVowKorP48unedr6KiAkexNT+AffKzL6QxIkPj63MJ+jKbm2CqzS2+sjLf8jXQsNwDl8UrNFDGA7CQ+pb2rxMkPf/u8IE=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale