apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: anymus-rke
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  type: kube-apiserver
  replicas: 2
  kubeAPIServer:
    mode: auth