apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      metrics:
        enabled: true
        service:
          enabled: true
          port: 10254
          labels:
            app.kubernetes.io/name: rke2-ingress-nginx
        serviceMonitor:
          enabled: true
      service:
        externalTrafficPolicy: Local
      config:
        ssl-redirect: "true"
        force-ssl-redirect: "true"
      extraArgs:
        default-ssl-certificate: "cert-manager/anymus-cf-cert"