apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      service:
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
        ssl-redirect: "true"
      extraArgs:
        default-ssl-certificate: "cert-manager/anymus-cf-cert"