apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: immich
    repoURL: ghcr.io/immich-app/immich-charts
    targetRevision: 0.9.2
    helm:
      releaseName: immich
      valuesObject:
        redis:
          enabled: true
        immich:
          persistence:
            library:
              existingClaim: nextcloud-nextcloud-data
              readOnly: true
        server:
          ingress:
            main:
              enabled: true
              hosts:
                - host: immich.anymus.pro
        machine-learning:
          persistence:
            cache:
              size: 20Gi
              type: pvc
              storageClass: longhorn