apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-cnpg-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/cluster
    repoURL: https://github.com/cloudnative-pg/charts.git
    targetRevision: 6014e4d5ad35e866df6312027c73c8fea71a341e
    helm:
      releaseName: immich-cnpg-cluster
      valuesObject:
        cluster:
          imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0
          initdb:
            database: immich
            postInitApplicationSQL:
              - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
            owner: immich
            dataChecksums: true
            encoding: "UTF8"
          postgresql:
            shared_preload_libraries:
              - "vchord.so"
          instances: 1
          storage:
            storageClass: "longhorn"
