apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-default-vol
  namespace: cloud
  annotations:
    volume.beta.kubernetes.io/storage-class: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/anymus0/anymus-rke.git
    targetRevision: HEAD
    path: helm-wrappers/immich-custom
    helm:
      releaseName: immich