apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmks
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vmks-victoria-metrics-operator-validation
      namespace: vm
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vmks-victoria-metrics-operator-admission
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  source:
    chart: victoria-metrics-k8s-stack
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.60.1
    helm:
      releaseName: vmks
      valuesObject:
        victoria-metrics-operator:
          enabled: true
          operator:
            disable_prometheus_converter: false
            enable_converter_ownership: true
        grafana:
          enabled: false
        defaultDashboards:
          enabled: true
          labels:
            grafana_dashboard: "1"
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
        vmsingle:
          enabled: false
        vmcluster:
          enabled: true
          vmselect:
            replicaCount: 2
          vminsert:
            enabled: true
          vmstorage:
            enabled: true
            persistentVolume:
              enabled: true
              size: 50Gi
        # Enable vmagent to scrape kube components
        vmagent:
          enabled: true
          spec:
            scrapeInterval: 30s
            resources:
              requests:
                cpu: "0.3"
                memory: "512Mi"
              limits:
                memory: "512Mi"