apiVersion: v2
name: immich-custom
description: A wrapper chart for Immich with custom volume mounts
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: immich
    version: 0.9.3
    repository: "oci://ghcr.io/immich-app/immich-charts"