apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.10.1
      helm:
        releaseName: longhorn
        valuesObject:
          global:
            nodeSelector:
              longhorn.io/storage-node: "true"
          longhornManager:
            nodeSelector:
              longhorn.io/storage-node: "true"
          longhornDriver:
            nodeSelector:
              longhorn.io/storage-node: "true"
          longhornUI:
            nodeSelector:
              longhorn.io/storage-node: "true"
          persistence:
            defaultClassReplicaCount: 2
          defaultSettings:
            defaultReplicaCount: "2"
            systemManagedComponentsNodeSelector: "longhorn.io/storage-node:true"
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system