apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.0
      helm:
        releaseName: longhorn
        valuesObject:
          longhornManager:
            nodeSelector:
              longhorn.io/exclude-node: "false"

          longhornDriver:
            nodeSelector:
              longhorn.io/exclude-node: "false"

          longhornUI:
            nodeSelector:
              longhorn.io/exclude-node: "false"
          persistence:
            defaultClassReplicaCount: 2
          defaultSettings:
            defaultReplicaCount: 2
          preUpgradeChecker:
            jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system