apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 9.1.5
    helm:
      releaseName: argocd
      valuesObject:
        redis-ha:
          haproxy:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
          enabled: false
        controller:
          replicas: 3
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        server:
          autoscaling:
            enabled: true
            minReplicas: 1
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          autoscaling:
            enabled: true
            minReplicas: 1
        applicationSet:
          livenessProbe:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          replicas: 3
        global:
          domain: argocd.anymus.pro
        configs:
          params:
            server.insecure: true
