apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/argo-cd
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: 4676fa5171dbc07d1ac7da7a4996561a6f2804dd
    helm:
      releaseName: argocd
      valuesObject:
        redis-ha:
          haproxy:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
          enabled: false
        controller:
          replicas: 3
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        server:
          autoscaling:
            enabled: true
            minReplicas: 1
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          ingress:
            enabled: false
        repoServer:
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          autoscaling:
            enabled: true
            minReplicas: 1
        applicationSet:
          livenessProbe:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          replicas: 3
        global:
          domain: argocd.icefish-pickerel.ts.net
        configs:
          params:
            server.insecure: true
