apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.0.1
    helm:
      releaseName: argocd
      valuesObject:
        redis-ha:
          enabled: false
        controller:
          replicas: 2
        server:
          autoscaling:
            enabled: true
            minReplicas: 1
        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 1
        applicationSet:
          replicas: 2
        global:
          domain: argocd.anymus.pro
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"