apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 21.1.23
    helm:
      releaseName: nginx
      valuesObject:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: ollama.anymus.pro
          ingressClassName: nginx
        replicaCount: 2
        existingContextHttpConfigmaps:
          - "ollama-nginx-http-cm"
        # Mount the custom server block ConfigMap as a volume
        extraVolumes:
          - name: ollama-server-block
            configMap:
              name: ollama-nginx-server-block-cm
        # Mount the volume into the NGINX configuration directory
        extraVolumeMounts:
          - name: ollama-server-block
            mountPath: /opt/bitnami/nginx/conf/server_blocks/ollama-server-block.conf
            subPath: ollama-server-block.conf
            readOnly: true
        readinessProbe:
          enabled: true
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          enabled: true
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2