apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 21.1.23
    helm:
      releaseName: nginx
      valuesObject:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: ollama.anymus.pro
          ingressClassName: nginx
        replicaCount: 2
        existingContextHttpConfigmaps:
          - "ollama-nginx-http-cm"
        serverBlock: |-
          server {
            listen 0.0.0.0:8080;
            location / {
            proxy_pass http://ollama;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            }
          }