apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-nginx-http-cm
  namespace: ollama
data:
  http-context.conf: |
    # Enable gzip compression
    gzip on;
    gzip_vary on;
    gzip_types text/plain application/json text/css;

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    # Map for WebSocket upgrades
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }