apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-nginx-http-cm
  namespace: ollama
data:
  http: |
    # Enable gzip compression
    gzip on;
    gzip_vary on;
    gzip_types text/plain application/json text/css;

    # Security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;

    upstream ollama {
        server 192.168.0.200:8080; 
    }