apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-cnpg-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/cluster
    repoURL: https://github.com/cloudnative-pg/charts.git
    targetRevision: 7aa517a05e50cff8df5bfa849e9dc18322dab240
    helm:
      releaseName: litellm-cnpg-cluster
      valuesObject:
        cluster:
          initdb:
            database: litellm
            owner: litellm
            dataChecksums: true
            encoding: "UTF8"
            secret:
              name: litellm-cnpg-initdb-credentials
          instances: 1
          storage:
            storageClass: "longhorn"
