apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-provider-keys
  namespace: litellm
spec:
  encryptedData:
    GLM_API_KEY: AgAu2IZSsw437TPluLExhhy2GR8YFXsFST4K+iJn+esJmm7SPqIJq8RkIW5shKlRYhUSQckhxs7U+TH1sRfrKVfKM2Y13NO1H9kOIrg18DVVyAEyfA9VbV+zTcTBsLqgLHThmp2UjJ2zcvlxZ0USBl2KmWHu50FvIxTob5afyDglFkT1SgPluft29ccXLTOy8fG1C1t4S8hjBMikuY8z4bhCuMX9wbkR8F4G4SUZDCz3hotrkcLjXLJVc1pYQJDvluRHDhLbm6nceLvRXX7PjgO952D4EZ3rKeDAa5YvhpIUAri27U8ALxUWJ7bsDih9ojornsBY0vBbDwXLPEA6ePzyOLzF5FrTrT0Vx+hmSYE3UnispuXGlTjuiIp7x3Y7FnhcKl/F3Jv7TPPFP3nUN/GF2OZFFSYIS5KRo3vbiLnmvzGdnaFN58+EHO7KulqpnF4Hh1+fCmz1GrvJLJrcBcffPf0C0Hs74RLeoOZZ1KOokWMl2xmTsbzKwaMwjr67NW4T8CtJJYLS8eYbn9AXkI0PinOvcCHMkpRZqyzzVodopG8bUIg2v4bFyvJk/TGRxCWinoh0zAM2i80AzfifXzqwW3lh1sKEU8L25DCcuKCvYzTZy8mje2paU7KyyBxk5lYg3wiDU6152n7NZd6ap8AASOcQ441RcEPkYqnYiGFL7BS3J4v70khPaQBfpYK7ob6o8bQP8Vk9G1UjTfrLR9b1BNllpT9N+SAkmm4Awa/uBNp5zJDS1tBGTrRhzboD0wyy
  template:
    metadata:
      creationTimestamp: null
      name: litellm-provider-keys
      namespace: litellm