apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-provider-keys
  namespace: litellm
spec:
  encryptedData:
    GLM_API_KEY: AgBa5T4Kh0bXpRgVI89nz+Q8baNuxavfQaa0aBDLMqAs/4zlx2v96f+E4JPfv4ie2guBosKwWOME4WC6SKaf+p34h8yUfvrQBsqLkiwtlW/27LUyEVyI/YJPUtevnTNKVPFhXOLJkk4sTXET33Npz/inoqohUubc6+cMxi4cUNeIESLR0+tcudylMuHRAtVmE1ur4ZntsGE+uwfaUAMpuRzo2n8/YjGG0SNNaVt+w8EEJWlb0hC7CaD7XEYXRqGLU6igVaMURvDldMJCxZGUdNCtmcuFdCzZNQONo2o9XqpKoriY2I889kROlywsJ/j3NBKeeiu95e+BMtIjV2M33ckkdDj/w68yj5/uIXGZb9TWcBbLfLn2WMW2O0kRs3F1nwCTOZZCPPfYeRJSofiaGhYC7zUlOYTjm1rQraiXrF7JsuPtvbZMNXsvTTBBvcvhcDy9TkuqfqDq3yI4J522yKobD33nh3nANf5GlOnb799o/uex3bcytz0lO+D6kb2MGP+6bFjjMCTZKis9om0rOEvYKTtsU48ooyYA3Wc0BseIoGkhW0uFH8XYCTwKbPtTuEx6cJ3jjhxmSzIlYh6JGxPvMo13rRGjRzvHU585TfLLFnRwe4vkNeg4+OHQznBELbOFp6y4GxbEbXQ3qvNWP6g4ylxiU6l4vdNHDoTrKKeIEP03x2ZpYJZX2rVRBebaimOejJVtykR3xBipaVu3cy2WjqamdHYFgLRo0fSPoAuk56zzgBGXlCyN6seZC/cGi2MaMs7quEwTfxQ0Potxvb3sdZpJ5w==
  template:
    metadata:
      creationTimestamp: null
      name: litellm-provider-keys
      namespace: litellm