apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-ui-auth
  namespace: litellm
spec:
  encryptedData:
    UI_PASSWORD: AgBZR9xuHWO/1aXm3eoKS9X8NkFhMGLhQ8NlVpvi+Erd2DzceWELnLbAazvIr0NJa3U01KmB1s1DNmLZHz2/ViS89wxFFke51wog8IJCZhFYfdMqpcM2BPCOhxgA1Zw13JH651CNh8Kz4+RQ9UchWjLUaF+laWU3LJHLwrz49UzoCr0FZgeMxzHOBRohrCcZpYxIddmn9o5V/M1LWofjnOZaLHJb3HX5gA9XmW9TmJHwdVomgqDzhEE9yWGSlsoYINn3lnOnHNYQ4Omuwag6Tayj1Yq2joN7APrbSfCuZJza+hphMQjwdqrX3GOKiYyEnEqJ/Jg1KkYREY+3SYjHWjOaMrRDN77lKfnOocuztNmtRWaLUjiEdmX5pWtXLKAFeuVj4L+54P7yr5tSj7f4huv0WTZYCPB4mcbFTL66fd/kOiL/WFBwCmPmlIs0ic9i6Ualp3ibKa9IQUonVte6KTiIEsrrm16GTQrQCUc5bMb5cTYC+SPGzFON87ggXqotv75fEaOVykG7ie0mTZbipBnPkYu1zVRGA5e1VR1KIEcPo9dk55PsBVhjF2Q10zX3chyAflQRYCg5a79MrO4jUKtpaqKadS7W0W2bSXL70LPINoAXPSMAJ4E3EWaffMloV1xT6+/KPjIiJKRDEjP07EemknA86w04meYapXWC4uUj/7lyTsbWZANscg3f5/5S5lqsnHwYNmyUf8mJNnVY5b380LeljN301uZa+jRfJxuc
    UI_USERNAME: AgBDRHQQ6HS6oIa/eP4EzAt/3gJVcXz4Jtq5rOnIAzsE9Cj1Pz9VoyWC5T6W1rv8+93Bhh5tia3lOkyt7of42kZnbvXb7BidY2CvOu9/GpcopVWygy0iE62lxtp+en5F4z9RQ3V7Si3UkjZX+4qzayC1aUTC1H9zWWb2ifhHun9qCZl9wOUV5lJtHSblA0DwtOInvvxdXMcSxFhxsPpMVciyCotaD2caj1jdyMObgAWFT1YFDgZyCdZb+ZqISoaqKLMziJqTqyBYC91vd6s9gnScVqjJDpGxmGpGnUMFK1Jf5rX0GDKKc01gx4ygKoHjDQoiRes+q0odA07yuLPoxLj4+1cjMb59B3iOG4qrtiohBKZWHlwJ0dUShwppy3DxbAtfFJtXVZB1u1avGvf4Eu4XoCNv1MbbScda1vget26q6t0wkOFz84Wmywun7UG37M63l2Nu+9QBdEEWVEd9TMFMrJHKPHsyKD5Z8bHwVIx0EeqT4bxcBAKQ4OFjfMRRMqYGb9yMhYFuyUmDTf+qEt/8+g/bh+UokU2/wQLBa8oTV6H5qEzJ22QfGQl8pidjQbLHySEorWmwm08sms2Xu0iF7qXMZVbtIPIyB/431uTIa11HQY13xNsQWNbASzqBhBE0kD60UpjUqPi+wMVneC95p8ajn5ZmbtcJtD87J6E+qUs1LmZ6S720E9Aw6fFeQv0ELeHFmBM=
  template:
    metadata:
      creationTimestamp: null
      name: litellm-ui-auth
      namespace: litellm