apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-cnpg-initdb-credentials
  namespace: litellm
spec:
  encryptedData:
    password: AgCo/UhBqL+s+Cvx9E32EGgiy3X5V/rIntC/m2TMxDbSPv4t7oNcbyYM9v05fecNOlRaXN6X4Nc2eh77vaD3PFYGti59Dt8H0X1gIDKmsQc+f7epAi/wAnBIuFtQUwuvyUmyRFIdX0+iawVT7+8lFWlYd4Pi4VlwWQDGMMz9OBlY5h4Cg++CDEO/xFyrtRwY3VrltrSdpjGBQOtzFzN1Zy2Oyh4XLqrnazD5mpqTcoSW7AygtaDn912lEVuiF7wucNCoPBZsLlNqFyCdPT0ic90/CNZI5mj8QxXgzNWndWjgPYtvBHwCPS2jOs9VAb19P0EEL4F9DWBOtBzQvMqM0g+mVuDeiP072GRAoE4sxBWxSnjgWYTV+iN8EWNhsTWDrSFTKRVJsfwbtfOq5URyvS4TxO0Q8U1YIWXWrBv7wDOlLiEGtkx2CS6Xk+Pc+3jpIiGZOH4Zsk0MceLTABxQUIlI0xZEhE3z2shr9p6f21RHDeT+Hirogpwiq592GUp3+U+9HI80Q8BUHs+KXlU4XQ7eTkKONmGpRAz9rCMsNFaA1YKKfhhMYXRzxsmVeV37m/76OLHLhuoRPLragULJ750OMZYY5mIkoZWiBa+XSvNrHBPm4eJBSTODpFg0c65dEGdfDq6+UvKOyoH6KXyaucWVjHK3hLcg0dhx21OT/a9A0KHcCB7h6tYecR/S8gBu6/lvP6L6eF0vzOOctMBxiJ/N+jNznIC4t0Us8q+muEJj
    username: AgCAaZPjJqEUC5jUvEpOaLF8f2QJF4SlGahVkxqjznnIfMvZfqZmapRtVQ12HZGE28LXcgdt96bxXP+fNVB4Tj007vfup/sYO7U47QJ5ReAWCG9Wq5ZRvyU3/8bq3Jp5jJcJV8K9H38e6cucTSDuOiKXa37FFtR9h8+pcQAi0S8WTlw644ap+EuXj8nckTZOdkr2bY1jwXTNo0OaI/ZruJtALbZyGFRmArWJEVZfRnz4T/9eqAigFQBQcoCu+zWiWYJfAXsCCCZUHQwLcdRQvqwq5uTYUdkuhCMEpM3zQNx4UxJha3DRG527PurNkDeYbtLodbMJ+eq0SKzLUGtyyjHhyQpp48UGJqDVXrDs93as14rt3gvFq25cLzcvnQUfUsrwtU2HRUGeXhIJsjPg4fMhZtroWM5+JzMfbHNC7cbsRqxMM2ol1ikTCzFQSB4c6sBFKnvSMLdar/8vC90mOM6BP0dfXPCRXqXugInwvvpeg+DofX2wbXBRxEbMpjZoa6j++b/52hIeMbb5s21t/K0SJ66OIjHM4hJpfAW/NE1HH7WwHUN6eo14vmYVtFjJ3xi9Gby8bNFFhPtdlBPVY25TuTresH+crUO1y6Ri9UigCVzca2CSOrYKEWilP4IAKUU4WkciWlKp4PpDgnalUto4/YBcB8DqeaMD0zianf5b7nOVLtpQUN3PlqsK2Q+v1Z3WHlERTEtO
  template:
    metadata:
      creationTimestamp: null
      name: litellm-cnpg-initdb-credentials
      namespace: litellm