apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-masterkey
  namespace: litellm
spec:
  encryptedData:
    masterkey: AgBiPimxsD6FOK2CCw1nhhhGnoEcgq+tm3LGDe3WoCT3astSHncJUQRMgQig8zuB68kEjf4JPL7hFZtsULIk9493iqpjPx9N6B8+/ZrkrY8GC9S/qvibv/z2kLcXLBIL74hg5C1G+2alkVZviUXA59GL/TCP07jBibanS0cusKmrMlvJ+1NiGpVjf3mALpBv8jUXbQzD4xvGFCaMize3v1SdiNeeDkonUXbKgFL6jHjMuTi+AjZoUOvr0ZQqogoobvlfH/kOwezOKhCFMWup2bHZO4S/AwK+kaMaRKV1Pv9s68Gc2dL+rLl7bPdL0wNzpcevfSDLtYWhLGdsgdldt9hK3lQ6Wfus0UBc49rzYcuQpbksaxBg4FWwslIYy8ECE4S260mCTADzfT9nhWk2T5DVwKTaGYIw/+dUtUzW7N8PlPDq+hqmHlQzLufk49dyNTA/RnkZ8SkF0c6tox++ngwW37xR8pHiW/cGumxfT5LTXEeJjQgts7rltUkddCe/rlti+7SoBtl7H9oaLkIdl7F4FrwMxru9SRbLY+ON8uOm/CK2jQMhiY5eI8H1ZzghZrnm9BKwAq/F1mdW8F+7ph3ijCLHWRiEILqoPW4LN/A/pF9i6rQZCF/0peAc58zNcAfsCvix3+UrBySDDJoMrBq8Hi2VaG8X9bRjge2LKDkHCafZ1Jhp2S8jYoQiGultKoTRr56Lj0KZtC7PCf+qBpGUgUtO+eERh3dPAm2r1fB0gevJwjrNerX4v0IKG/RhjcvUAHgQ
  template:
    metadata:
      creationTimestamp: null
      name: litellm-masterkey
      namespace: litellm