apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgA6vPB9cod3aF/70Gg5lcJxyP1l7ix3cq6Ftia4R8YWZV/xELQ405NTLSAXRmc3/Vwv+wPpy4fcXTRbHLkeDMdHZ15k8745s0+4L/rNge9mVoqsEwNrUv0VslFMoBxV4zzBvX5cnEtILFz9g1SgOOun5RKoscKugl0jIPlnZ/iLiOVl9XleFy/rNXJHwzV5yPgFhVtXYU2Wd+AGU/udePM/AUt6/7OMUzbElqSm2uqWmtqQFtCLy8tHwNC9dhsx65n79oAEeU5Xm7LLBtrPale/tvhJda6UX50lH2IdPCQhFOTVF7DLctqkSJpk2fOJXRk6LaJ5L5ebuy2aJpoWCbSCL+TfoagZnE7f6BoWmV4rfnAeHg41/TMM0IjgI5HPENWin/ghitWWV6kOu1gzT3ZJf8ZfWxZGRjr2y3WhE4hEXBZ1Pl8oJ0pX6r/Bk1HIMTJJvD9vF1/L9Clz8wELbYNsVfErKlVleRIIaHPtQqbNF+pQtd0qUk3dErWSklTbQptBi0ihKAEeIIizkB8YfiDiSxNMUJJbQ9YrW8kex+ty0HZRGEb6m/h5g22s71hqrnCVYnuJdQP27JAbdGLGLT6o5adZD0/uVKG795OC61a+cqI9f8HnPNzwfSiesUq0GLEBdMyHie/OzX3+bx2jmnXPpDwy0ivj1uR/IM/KGtLPJUn4IVSZlLoFs6xAJwaNo+DkgHMYNL8i1gc7vK22hgBzmOlVMhhCm8pCqg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-secret
      namespace: harbor