apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-cnpg-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/cluster
    repoURL: https://github.com/cloudnative-pg/charts.git
    targetRevision: 7aa517a05e50cff8df5bfa849e9dc18322dab240
    helm:
      releaseName: harbor-cnpg-cluster
      valuesObject:
        cluster:
          initdb:
            database: registry
            owner: harbor
            dataChecksums: true
            encoding: "UTF8"
          instances: 1
          storage:
            storageClass: "longhorn"
