apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: helm/sealed-secrets
    repoURL: https://github.com/bitnami/sealed-secrets.git
    targetRevision: 8e4ed463552a6a6462648a9ff090a1f42abbda30
    helm:
      releaseName: sealed-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
