apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crw-auth
  namespace: crawl
spec:
  encryptedData:
    CRW_API_KEY: AgCezRKInYSGn+Wu08jXdQmQ/3SUweaqXvbsfNr7xC+igYkU38InX80zr5L0p1k06VxuPRLpEqX6TEqxcA/4BYGcC1qNjam9wjZKDBn5vG/OwIFTbkJmIBoj7QMuh+d9NhmLqcmeATKmrCazAFEf9XlAUdt5iFbTZGs48aqUO8WRexvkkKBprCs6Pnhg/YeSTL16pqt3Wv/cpV6VGA/AbO44HegDfsrw5rmKkkV3uS/bSi1YEPdVa7mAt221ol9Du3p/8bh4dMqJaEQFVriSoN3+cz7D5w154t5TWYFc10gM2ao53qV4neW1C6donySmnhhrZNw9Sy6icEHfl0zHDMGZBxHScBAprXfUHW8Djj34MRO0TnnZJQApYLLjhzLsN/NQGDV60IKH19jVHK73h88/O61zwGzcFloNIhNx4gAnXln5QBnitBbR9IOkzJ2M8V8/iMUnBTczDZ8A3qzoSp8ScCKUUNzjDUquCnLSSqsz9wDxAn8uflaxNIjKQBz4icFUwDVrNX2/Pdqru0UbYgwqADn6RqxFz8q5guQRQJiVPuKrmbjvchjRp4h/ogwJUbQRoeg/vuf8JXbnBOgKUum5+1SC1Lw1xqIaoSWHtFCWi1zq7PVWZfzDLBg+enCXMT0T5NifGHWtp1HCLobYHM5kvEtgFY/18fPs6xqnX262S7buM5AjGywxKawdQxfr5mq2jAcM1mn2w28ZXGvM6YYQuj37QyhDs894nQj9JA0E
  template:
    metadata:
      creationTimestamp: null
      name: crw-auth
      namespace: crawl
    type: Opaque