apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-auth
  namespace: crawl
spec:
  encryptedData:
    SEARXNG_SECRET: AgChgXuESru++kNBJQNnNvmuzxsb40Ho/dGwR3aMrNuaA/Fktv3QlrW+H7XKK+QBcLkNQ3qBDwbtRzqqwRlt/HUHJfaRTrfhnanhZgPTwxmT6zpeOUSC5nyMm9gskJyBxfU1TF7oBk5hRIZhdFKnk9KvLlhgegJukFVxZdFlt3O6cmSX3s/qGhjscRMGCbrGK4ShAdXyj0dqz8/vW3xKQUmCarhPltcj6+g4p6jcM08kgsO6t3VuOob9ud8KNyPqFP/Rm0Th4Z+Tu5/eVK9KouNv/S4Ih6IW0lRcxovNU2j+aIQaK/y4Gadba/irhqJeKUra+ESDPHWPaEB+Lg42v41eMTxuQF6MSWaP7Dha6bdGRXsnAlNjng3C2LbNLYAbZwBpNgP9C5Fg2H5Id/0hjWAW+34bCr8CPOnw/+w/SRIe0GH4kozIJzjdoDY/oGF3/PXVh4cZUH3YYY9/5kftnjmez3BBvpifyMGAAt2xRb9h38dRkKA4xfGDT4gf/oWNKIr8FtvY2cUQGyqO+Y2ejCJxJzexKr6k7azS3RjQVfzclO8mlv3efsxaPooHGnYL60DqUSCQ9WwuqIo/KWgVQAI49/3BbrtgTLVyp4OGEZmb9bObjqTR1kYD9AV+QK6nNqw0oIkjEx2DzWCqXKMS3EufwQXkcanGKyW4j0pM/9nwinDo5vD5gNHBEYP+NWUqEznIq3xI61dDlvwwT3C3pMKkT1AuOEuYWkfo97h3c/Ho
  template:
    metadata:
      creationTimestamp: null
      name: searxng-auth
      namespace: crawl
    type: Opaque