apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hajogepesz-wp
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hajogepesz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: wordpress
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 24.2.6
    helm:
      releaseName: hajogepesz-wp
      valuesObject:
        existingSecret: hajogepesz-wp-creds
        mariadb:
          auth:
            existingSecret: hajogepesz-wp-mariadb
        persistence:
          enabled: true
          storageClass: longhorn
        service:
          type: ClusterIP
        wordpressConfigureCache: true
        memcached:
          enabled: true
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: "hajogepesz.com"
          path: /
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/ssl-certificate: "hajogepesz/hajogepesz-com-cf-cert"
          extraHosts:
            - name: www.hajogepesz.com
              path: /
          extraTls:
            - hosts:
                - hajogepesz.com
              secretName: hajogepesz-com-cf-cert
            - hosts:
                - www.hajogepesz.com
              secretName: hajogepesz-com-cf-cert
        secondaryIngress:
          enabled: true
          ingressClassName: nginx
          hostname: "hajogepesz.hu"
          path: /
          tls: true
          annotations:
            nginx.ingress.kubernetes.io/ssl-certificate: "hajogepesz/hajogepesz-hu-cf-cert"
          extraHosts:
            - name: www.hajogepesz.hu
              path: /
          extraTls:
            - hosts:
                - hajogepesz.hu
              secretName: hajogepesz-hu-cf-cert
            - hosts:
                - www.hajogepesz.hu
              secretName: hajogepesz-hu-cf-cert