---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anymus-cf-cert
  namespace: cert-manager
spec:
  secretName: anymus-cf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsZones:
  - "anymus.pro"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hajogepesz-hu-cf-cert
  namespace: cert-manager
spec:
  secretName: hajogepesz-hu-cf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsZones:
  - "hajogepesz.hu"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hajogepesz-com-cf-cert
  namespace: cert-manager
spec:
  secretName: hajogepesz-com-cf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsZones:
  - "hajogepesz.com"