---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anymus-cf-cert
  namespace: cert-manager
spec:
  secretName: anymus-cf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.anymus.pro"
  dnsNames:
  - "*.anymus.pro"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hajogepesz-hu-cf-cert
  namespace: hajogepesz
spec:
  secretName: hajogepesz.hu-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "hajogepesz.hu"
  dnsNames:
  - "hajogepesz.hu"
  - "*.hajogepesz.hu"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hajogepesz-com-cf-cert
  namespace: hajogepesz
spec:
  secretName: hajogepesz.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "hajogepesz.com"
  dnsNames:
  - "hajogepesz.com"
  - "*.hajogepesz.com"