apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: anymus-cf-cert
  namespace: cert-manager
spec:
  secretName: anymus-cf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.anymus.pro"
  dnsNames:
  - "*.anymus.pro"