---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cf-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBailwRo3KbUOEhzCTNGuM8ck7smGSTlCstBChfikJGhChQuyVq77p2JY9cO+MZCGjrlq/mrvatJDuMYU4wUpaCbFypDn3WsBTqaM7VzgOrSJna7E6+rQMK5S8RrHCOolDaFMXCSNgM3FJ07McYKw7MXD1dK+3bgtR6MhV2tB7PyF+2XO1BYWwl6cnnyPEVA/rkz6ltpAPzUpLtq9Ujjf5fD9eIMDjoQASm+7SDzz/FJ/PQXUp585XN9hly4SQOKam9IdpQbjdt3pRgOhLpxjYwi7aGUHJ9Z1D/Q+JSprNS9KsexXD186sdOPJjL2opqDz4m59XYasb/ODZhDBzBHsuDQ3y2NKVbV+oepLtsGcSGR4jQxU0MWCykEwQ887ubSf1ccfq1zTcL7GWUVKzxIFVhCoDna5118J/0zrHRVqaDxGQG7cxfzlfp8q9Vm8fWmUD1x0bsx5meXf5TfjB+daJqxDLZoJHGIHMDdsbGPv5vKnG9Kh5s2l5mSSuTykmpMNbrnw9iDDXQ8SRmv57qGoSbEIKeJOaNlC2AVFEJ4x+xsqKe3k18L8N6VothCk22t2PnFzxAxRdKxR5X1acu0A0o7691LTQCALZOZ6TBmphV08OxBEagPaF2LdbBXmNb87rNxedbhuo/Xm+xDBeNP5NIGmqhAvTZCrBN7lRp3vYl3sj2gpBiyrwjUloCowLsIM6nTnvhF40iNoq1KI4QaghHEdNBfvlPzXrzkN+KKRv8bSui7pz6Xkc
  template:
    metadata:
      creationTimestamp: null
      name: cf-api-token
      namespace: cert-manager