apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ocis
  source:
    chart: ocis
    repoURL: harbor.anymus.pro/anymus-helm-pub
    targetRevision: "15"
    helm:
      releaseName: owncloud
      valuesObject:
        replicas: 1
        externalDomain: ocis.anymus.pro
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
        services:
          idm:
            persistence:
              enabled: true
              storageClassName: "longhorn"
              size: "1Gi"
          nats:
            persistence:
              enabled: true
              storageClassName: "longhorn"
              size: "1Gi"
          storagesystem:
            persistence:
              enabled: true
              storageClassName: "longhorn"
              accessModes:
                - ReadWriteMany
              size: "10Gi"
          storageusers:
            storageBackend:
              driver: "ocis"
            persistence:
              enabled: true
              storageClassName: "longhorn"
              size: "50Gi"
          web:
            persistence:
              enabled: true
              storageClassName: "longhorn"
              size: "1Gi"
        features:
          demoUsers: false