apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/open-webui/helm-charts.git
    chart: open-webui
    targetRevision: 1141e87d4ff460a1cd00e4130ad013c63e0153c5
    helm:
      valuesObject:
        ollama:
          enabled: false
        ollamaUrls:
          - http://192.168.0.200:11434
        ingress:
          enabled: true
          class: nginx
          host: ollama.anymus.pro
          tls: false
          existingSecret: ""
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: open-web-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
