apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/open-webui/helm-charts.git
    path: charts/open-webui
    targetRevision: c328f1ba7d6b6eafc6f3d339fafcd3514bddfc95
    helm:
      valuesObject:
        ollama:
          enabled: false
        ingress:
          enabled: false
        resources:
          requests:
            memory: 5Gi
            cpu: 4
          limits:
            memory: 5Gi
        extraEnvVars:
          - name: ENABLE_API_KEYS
            value: "true"
          - name: WEBUI_AUTH
            value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: open-web-ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
