apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloud
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  source:
    path: charts/cloudnative-pg
    repoURL: https://github.com/cloudnative-pg/charts.git
    targetRevision: 6014e4d5ad35e866df6312027c73c8fea71a341e
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        crds:
          create: true
