apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: cluster
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.3.0
    helm:
      releaseName: cnpg-cluster